title: "[Feature]: "
labels: ["Ideas"]
body:
  - type: checkboxes
    attributes:
      label: "I've already checked other feature proposals"
      options:
        - 'Yes'
        - 'No'
  - type: dropdown
    attributes:
      label: Is your feature request related to a problem?
      options:
        - 'Yes'
        - 'No'
  - type: markdown
    value: |
      "A clear and concise description of what the problem is. Ex. I'm always frustrated when ..."
    attributes:
        required: true
  - type: markdown
    value: A clear and concise description of what you want to happen.
    attributes:
      required: true
  - type: markdown
    value: A clear and concise description of any alternative solutions or features you've considered.
  - type: markdown
    value: Add any other context or screenshots about the feature request here.
